# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Aman Desai
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "amandesai01.github.io" # the base hostname & protocol for your site, e.g. http://example.com

twitter_url: https://twitter.com/aman_desai_
github_url: https://github.com/amandesai01
facebook_url: https://www.facebook.com/aman.desai.969
instagram_url: https://www.instagram.com/mrwinnsome/
linkedin_url: https://www.linkedin.com/in/aman-desai-66a333173/
cv_link:

phone_no: +91 88881 89687
address: Amravati, Maharashtra, India
email: aman.desai@somaiya.edu

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
